### ISSUE TITLE
Run emp-ot in one process 

### ISSUE THREAD

**Issue by ilot95** [emp-toolkit/emp-ot#13]
For testing I wanted to use emp-ot in one process. I modified shot.cpp for threading.
[shot.txt](https://github.com/emp-toolkit/emp-ot/files/1482112/shot.txt)
When I run the server and client in different processes everything is fine.
But when I run them in the same process I get the following  error:
/Users/tilo/gogar/emp/emp-ot/bin/shot 0 22465
connected
connected
NPOT	NPOT	FATAL ERROR in /Users/tilo/gogar/emp/relic/src/bn/relic_bn_div.c:139

Process finished with exit code 8
The Stacktrace:
![shot](https://user-images.githubusercontent.com/24399001/32945737-e08b29b2-cb94-11e7-963c-3ad6b836fed8.jpeg)

It seems to be some kind of division by zero exception in the relic code. 

Note that I am using MacOS 10.12.6 and USE_RANDOM_DEVICE.

**Comment by wangxiao1254** [comment]
I would like to first try if the problem is indeed relic. You can swap OTNP by an "insecure" OT functionality class called `OTIdeal`, which does not use relic. (To do this, just change `OTNP` to `OTIdeal` in the header file for shotextension, and change related headers.) If it works in the multithread version, then it has to be some problem with relic. We can continue from that.

Just FYI, I indeed have code where relic is involved in some multi-threading programming.

**Comment by ilot95** [comment]
When I swap OTNP to OTIdeal everything works fine. 
![shotex](https://user-images.githubusercontent.com/24399001/32991208-626f6aee-cd37-11e7-88b9-7a9cf31d9dcf.jpeg)

**Comment by wangxiao1254** [comment]
Okay. I was able to reproduce the problem and found the solution. The problem is that when compiling relic, it is by default setting -DCORES=1, which means no multi-threading support. If you compile with -DCORES=2, everything works fine.

It seems not always needed, because I used -DCORES=1 and multi-threading relic for some problem before. I think in this case, we are running different code from both parties in the same process and that might cause some data racing issue.

Anyway, please try and let me know.

**Comment by wangxiao1254** [comment]
In more detail, look at https://github.com/emp-toolkit/emp-readme/blob/master/scripts/install_relic.sh

and add -DCORES=2 to the line with `cmake ... .`

**Comment by ilot95** [comment]
I tried this and it does not work for me ... :( (I get the same error as before)

![olderror](https://user-images.githubusercontent.com/24399001/33017766-de700740-cdf3-11e7-9ca1-398a9937bfa0.jpeg)

[install_relic.txt](https://github.com/emp-toolkit/emp-ot/files/1487496/install_relic.txt)

I found this in the cmake of relic:
-- Supported multithreading APIs (default = UNDEF):
   MULTI=         No multithreading support.
   MULTI=OPENMP   Open Multi-Processing.
   MULTI=PTHREAD  POSIX threads.
When I set -DMULTI=PTHREAD it crashes a little bit earlier. I cant set it to openmp, because there is not support for openmp in standard apple clang.
![new error](https://user-images.githubusercontent.com/24399001/33017863-521df224-cdf4-11e7-9c48-a2ff08a66b89.jpeg)

**Comment by wangxiao1254** [comment]
Please make sure to `rm -rf CMakeCache CMakeFiles` and retry. If it still happens, I will try to pull up a fresh machine to verify. If it still happens, we can see if there is any cross platform issue then.

**Comment by ilot95** [comment]
Does not work for me. I even deleted the whole relic folder and ran the new install script.

**Comment by wangxiao1254** [comment]
This is reproduced. No plan to handle it in the near future as the program should never be run in the same process.
